// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	db "github.com/wallacebenevides/star-wars-api/db"
)

// ClientHelper is an autogenerated mock type for the ClientHelper type
type ClientHelper struct {
	mock.Mock
}

// Database provides a mock function with given fields: _a0
func (_m *ClientHelper) Database(_a0 string) db.DatabaseHelper {
	ret := _m.Called(_a0)

	var r0 db.DatabaseHelper
	if rf, ok := ret.Get(0).(func(string) db.DatabaseHelper); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(db.DatabaseHelper)
		}
	}

	return r0
}
