// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import primitive "go.mongodb.org/mongo-driver/bson/primitive"

// ObjectIDHelper is an autogenerated mock type for the ObjectIDHelper type
type ObjectIDHelper struct {
	mock.Mock
}

// NewObjectID provides a mock function with given fields:
func (_m *ObjectIDHelper) NewObjectID() primitive.ObjectID {
	ret := _m.Called()

	var r0 primitive.ObjectID
	if rf, ok := ret.Get(0).(func() primitive.ObjectID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(primitive.ObjectID)
		}
	}

	return r0
}
